version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      # Ignore patch upgrades to reduce noise
      - update-types: ["version-update:semver-patch"]
        dependency-name: "*" # Match all packages
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      # Ignore patch upgrades to reduce noise
      - update-types: ["version-update:semver-patch"]
        dependency-name: "*" # Match all packages
