[tool.poetry]
name = "team-roles-sweep"
version = "0.1.0"
description = "A tool to automatically assign 2i2c Tech Team members to various Team Roles"
license = "MIT"
authors = []

[tool.poetry.dependencies]
python = "^3.9"
slack-sdk = "^3.15"

[tool.poetry.dev-dependencies]
rich = "^12.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
